grobarting/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//:::::::::::::>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Frontend
Route::get('/', function () {
	    return Redirect::intended('/en/home');
});

Route::group(['namespace' => 'Frontend'], function () {

	require(__DIR__.'/frontend/main.php');

});


//:::::::::::::>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Control Panel
Route::group(['as' => 'user.', 'prefix' => 'cp', 'namespace' => 'User'], function() {
	require(__DIR__.'/cp/main.php');
});

grobarting/app/Http/Controllers/User/About/AboutController.php
<?php

namespace App\Http\Controllers\User\About;

use Auth;
use Session;
use Validator;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;
use App\Http\Controllers\CamCyber\FileUploadController as FileUpload;
use App\Http\Controllers\CamCyber\FunctionController;

use App\Model\About as Model;
use Image;

class AboutController extends Controller
{
    protected $route; 
    public function __construct(){
        $this->route = "user.about";
    }
    function validObj($id=0){
        $data = Model::find($id);
        if(empty($data)){
           echo "Invalide Object"; die;
        }
    }

    public function index(){
        $data = Model::select('*');
        $limit      =   intval(isset($_GET['limit'])?$_GET['limit']:10); 
        $key       =   isset($_GET['key'])?$_GET['key']:"";
        $from=isset($_GET['from'])?$_GET['from']:"";
        $till=isset($_GET['till'])?$_GET['till']:"";
        $appends=array('limit'=>$limit);
        if( $key != "" ){
            $data = $data->where('name', 'like', '%'.$key.'%');
            $appends['key'] = $key;
        }
        
        if(FunctionController::isValidDate($from)){
            if(FunctionController::isValidDate($till)){
                $appends['from'] = $from;
                $appends['till'] = $till;

                $from .=" 00:00:00";
                $till .=" 23:59:59";

                $data = $data->whereBetween('created_at', [$from, $till]);
            }
        }
        if(Auth::user()->position_id == 1){
            $data= $data->orderBy('created_at', 'DESC')->paginate($limit);
        }else{
            $data= $data->orderBy('created_at', 'DESC')->where('is_deleted',0)->paginate($limit);
        }
        
        
        return view($this->route.'.index', ['route'=>$this->route, 'data'=>$data, 'appends'=>$appends]);
    }
   
    public function create(){
        return view($this->route.'.create', ['route'=>$this->route]);
    }
    public function store(Request $request) {
        $user_id  = Auth::id();
        $now      = date('Y-m-d H:i:s');
        $data = array(
                    'en_name' =>   $request->input('en_name'),
                    'kh_name' =>   $request->input('kh_name'),
                    // 'cn_name' =>   $request->input('cn_name'),
                    //  'en_title'=>$request->input('en_title'),
                    //  'kh_title'=>$request->input('kh_title'),
                    //  'cn_title'=>$request->input('cn_title'),
                     'en_description'   =>   $request->input('en_description'),
                    'kh_description' =>   $request->input('kh_description'),
                    'cn_description' =>   $request->input('cn_description'),
                    'creator_id' =>   $user_id,
                    'updater_id' =>   $user_id,
                    'is_deleted' =>   0,
                    'created_at' => $now, 
                    'updated_at' => $now
                );
        Session::flash('invalidData', $data );
        Validator::make(
                        $request->all(), 
                        [
                            
                            'en_name' => 'required',
                            'kh_name' => 'required',
                            'cn_name' => 'required',
                            'en_description'=>'required',
                            'kh_description'=>'required',
                            'cn_description'=>'required',
                           
                            
                        ])->validate();
        
        if($request->input('active')=="")
        {
            $data['is_published']=0;
        }else{
            $data['is_published']=1;
        }
        

        if($request->hasFile('image')) {
            $image = $request->file('image');
            $imagename = time().'.'.$image->getClientOriginalExtension(); 
            Image::make($image->getRealPath())->resize(66, 66)->save(public_path('uploads/about/'.$imagename));
            $data['image']='public/uploads/about/'.$imagename;
        }
		$id=Model::insertGetId($data);
       
        Session::flash('msg', 'Data has been Created!');
		return redirect(route($this->route.'.edit', $id));
    }

    public function edit($id = 0){
        $this->validObj($id);
        $data = Model::find($id);
        return view($this->route.'.edit', ['route'=>$this->route, 'id'=>$id, 'data'=>$data]);
    }

    public function update(Request $request){
        $id = $request->input('id');
        $user_id  = Auth::id();
        $now      = date('Y-m-d H:i:s');
        Validator::make(
        				$request->all(), 
			        	[
                            
                            'en_name' => 'required',
                            'kh_name' => 'required',
                            'cn_name' => 'required',
                        
                            'en_description'=>'required',
                            'kh_description'=>'required',
                            'cn_description'=>'required',
                    
                         
                        ])->validate();

		
		$data = array(

                    'en_name'   	=>   $request->input('en_name'),
                    'kh_name'       =>   $request->input('kh_name'),
                    'cn_name'       =>   $request->input('cn_name'),
                    //  'en_title'     =>   $request->input('en_title'),
                    //  'kh_title'     =>   $request->input('kh_title'),
                    //  'cn_title'     =>   $request->input('cn_title'),
                     'en_description'   =>   $request->input('en_description'),
                    'kh_description' =>   $request->input('kh_description'),
                    'cn_description' =>   $request->input('cn_description'),
                    'updater_id' =>   $request->input('user_id'),
                    'is_deleted' =>   0,
                );
        if($request->input('active')=="")
        {
            $data['is_published']=0;
        }else{
            $data['is_published']=1;
        }
       
        if($request->hasFile('image')) {
            $image = $request->file('image');
            $imagename = time().'.'.$image->getClientOriginalExtension(); 
            Image::make($image->getRealPath())->resize(66, 66)->save(public_path('uploads/about/'.$imagename));
            $data['image']='public/uploads/about/'.$imagename;
        }
       
        Model::where('id', $id)->update($data);
        
        Session::flash('msg', 'Data has been updated!' );
        return redirect()->back();
	}

    public function trash($id){
        $user_id  = Auth::id();
        $now      = date('Y-m-d H:i:s');
        Model::where('id', $id)->update(['is_deleted'=>1,'deleter_id' => Auth::id(), 'deleted_at'=>$now]);
        //Model::find($id)->delete();
        
        Session::flash('msg', 'Data has been delete!' );
        return response()->json([
            'status' => 'success',
            'msg' => 'friendship has been deleted'
        ]);
    }

    public function delete($id){
        $now      = date('Y-m-d H:i:s');
        //Model::where('id', $id)->update(['is_deleted'=>1,'deleter_id' => Auth::id(), 'deleted_at'=>$now]);
        Model::find($id)->delete();
        Session::flash('msg', 'Data has been delete!' );
        return response()->json([
            'status' => 'success',
            'msg' => 'friendship has been deleted'
        ]);
    }

    function updateStatus(Request $request){
        $user_id  = Auth::id();
        $now      = date('Y-m-d H:i:s');
        $id   = $request->input('id');
        $data = array('is_published' => $request->input('active'));
        Model::where('id', $id)->update($data);
      
        

      return response()->json([
          'status' => 'success',
          'msg' => 'Status has been updated.'
      ]);
    }
   function updateDeletedStatus(Request $request){
    $now      = date('Y-m-d H:i:s');
      $id   = $request->input('id');
      $data = array('is_deleted' => $request->input('active'));
      Model::where('id', $id)->update($data);
      return response()->json([
          'status' => 'success',
          'msg' => 'Status has been updated.'
      ]);
    }
}

grobarting/app/Http/Controllers/User/Mailing/RecordController.php
<?php

namespace App\Http\Controllers\User\Mailing;

use Auth;
use Session;
use Validator;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule; 
use App\Http\Controllers\CamCyber\FunctionController;

use Illuminate\Support\Facades\Mail as MailSupport;
use App\Mail\PropertyMailing;

use App\Model\Mailing\Record as Model;
use App\Model\Mailing\Group as Group;
use App\Model\Mailing\Listing as Listing;
use App\Model\User\User as Creator;
 use App\Model\Mailing\Account as Account;

class RecordController extends Controller
{
    protected $route; 
    public function __construct(){
        $this->route = "user.mailing.record";
    }
    function validObj($id=0){
        $data = Model::find($id);
        if(empty($data)){
           echo "Invalide Object"; die;
        }
    }
   
    public function index(){
        $data = Model::select('*');
        $limit    =   intval(isset($_GET['limit'])?$_GET['limit']:10); 
        $creator    =   intval(isset($_GET['creator'])?$_GET['creator']:0); 
        $key      =   isset($_GET['key'])?$_GET['key']:"";
        $from=isset($_GET['from'])?$_GET['from']:"";
        $till=isset($_GET['till'])?$_GET['till']:"";
        $appends=array('limit'=>$limit);
        if( $key != "" ){
            $data = $data->where('subject', 'like', '%'.$key.'%');
            $appends['key'] = $key;
        }

         if( $creator > 0 ){
            $data = $data->where('creator_id', $creator);
             $appends['creator'] = $creator;
        }

        if(FunctionController::isValidDate($from)){
            if(FunctionController::isValidDate($till)){
                $appends['from'] = $from;
                $appends['till'] = $till;

                $from .=" 00:00:00";
                $till .=" 23:59:59";

                $data = $data->whereBetween('created_at', [$from, $till]);
            }
        }
        $data= $data->orderBy('created_at', 'DESC')->paginate($limit);
        //$groups     = Group::select('id', 'name')->get();
        $creators     = Creator::select('id', 'en_name as name')->where('visible', 1)->get();
        
        return view($this->route.'.index', ['route'=>$this->route, 'data'=>$data, 'appends'=>$appends, 'creators'=>$creators]);
    }
   
    
    public function create($id = 0){
        $groups     = Group::select('id', 'name')->has('accounts', '>', 0)->get();
        $lists     = Listing::select('id', 'name')->has('properties', '>', 0)->get();
        return view($this->route.'.create', ['route'=>$this->route, 'groups'=>$groups, 'lists'=>$lists]);
    }
    public function store(Request $request) {
        $user_id    = Auth::id();
        $now        = date('Y-m-d H:i:s');
        $data       = array(

                    'group_id' =>  $request->input('group_id'),
                    'list_id' =>  $request->input('list_id'),
                     'subject' =>  $request->input('subject'),
                    'message' =>  $request->input('message'),
                    
                    //Must include for all store
                    'creator_id' =>  $user_id,
                    'updater_id' =>  $user_id,
                    'created_at' => $now, 
                    'updated_at' => $now
                );
        //print_r($data); die;
        Session::flash('invalidData', $data );
        Validator::make(
                        $request->all(), 
                        [
                           'group_id' => 'exists:groups,id',
                           'list_id' => 'exists:lists,id',
                           'subject' => 'required'
                        ])->validate();


        $id=Model::insertGetId($data);

        Session::flash('msg', 'Data has been Created!');
        return redirect(route($this->route.'.edit', $id));
    }

    public function edit($id = 0){
        $this->validObj($id);
        $data = Model::find($id);
        return view($this->route.'.edit', ['route'=>$this->route, 'id'=>$id, 'data'=>$data]);
    }


    public function update(Request $request){
        $id = $request->input('id');
        Validator::make(
                        $request->all(), 
                        [
                            'subject' => 'required',
                            'message' => 'required',
                           
                        ])->validate();

        $user_id  = Auth::id();
        $now      = date('Y-m-d H:i:s');
        $data = array(
                    'subject' =>   $request->input('subject'), 
                    'message' =>  $request->input('message'), 
                     //Must include for all update
                    'updater_id' =>  $user_id,
                    'updated_at' => $now
                );
        
    
        Model::where('id', $id)->update($data);
        Session::flash('msg', 'Data has been updated!' );
        return redirect()->back();
    }

    public function trash($id){
        Model::where('id', $id)->update(['deleter_id' => Auth::id()]);
        Model::find($id)->delete();
        Session::flash('msg', 'Data has been delete!' );
        return response()->json([
            'status' => 'success',
            'msg' => 'User has been deleted'
        ]);
    }

    function sendListToAccount(Request $request){
        
        $record_id = $request->input('record_id');
        $mail_id = $request->input('mail_id');
        $list_id = $request->input('list_id');
        
        $mail = Account::find($mail_id); 
        if( $mail->is_subscribed == 1){
            $message = Model::find($record_id);

            $properties = $message->list->properties()->select('properties.id', 'en_name as name', 'is_published', 'slug')->where('is_published', 1)->get();
            if(count($properties)>0){
                $user_id    = Auth::id();
                $now        = date('Y-m-d H:i:s');
                $status ="no";
                foreach( $properties as $row ){
                    if($row->is_published == 1){
                        $data       = array(
                            'mail_id' =>  $mail_id,
                            'property_id' =>  $row->id,
                            'creator_id' =>  $user_id,
                            'created_at' => $now, 
                            'updated_at' => $now
                        );
                        
                        //$row->propertyMails()->insert($data);
                        $status = "Yes";
                    }
                    
                }

                MailSupport::to($mail->email)->send(new PropertyMailing($message, $properties));

                return response()->json([
                    'status' => 'success',
                    'mail_id' => $mail_id
                ]);
            }else{
                return response()->json([
                    'status' => 'false',
                    'mail_id' => $mail_id,
                ]);
            }
        }else{
            return response()->json([
                'status' => 'false',
                'mail_id' => $mail_id,
            ]);
        }

           
    }

    function sentDone(Request $request){
        $record_id = $request->input('record_id');
        $user_id    = Auth::id();
        $now        = date('Y-m-d H:i:s');
        $data       = array(
            'is_sent' =>  1,
            'sender_id' =>  $user_id,
            'sent_at' =>  $now
        );
        Model::where('id', $record_id)->update($data);
        echo "Sent Done";
    }

   
}

grobarting/resources/views/user/user/user/createForm.blade.php
@extends($route.'.main')
@section ('section-title', 'Create New User')
@section ('section-css')
	<link href="{{ asset ('public/user/css/plugin/fileinput/fileinput.min.css') }}" media="all" rel="stylesheet" type="text/css"/>
    <link href="{{ asset ('public/user/css/plugin/fileinput/theme.css') }}" media="all" rel="stylesheet" type="text/css"/>
	<!-- some CSS styling changes and overrides -->
	<style>
		.kv-avatar .file-preview-frame,.kv-avatar .file-preview-frame:hover {
		    margin: 0;
		    padding: 0;
		    border: none;
		    box-shadow: none;
		    text-align: center;
		}
		.kv-avatar .file-input {
		    display: table-cell;
		    max-width: 220px;
		}
	</style>
@endsection

@section ('imageuploadjs')
    <script type="text/javascript" src="{{ asset ('public/user/js/plugin/fileinput/fileinput.min.js') }}" type="text/javascript"></script>
    <script type="text/javascript" src="{{ asset ('public/user/js/plugin/fileinput/theme.js') }}" type="text/javascript"></script>
@endsection

@section ('section-js')
	<script type="text/JavaScript">
		$(document).ready(function(event){
		
			$('#form').validate({
				modules : 'file',
				submit: {
					settings: {
						inputContainer: '.form-group',
						errorListClass: 'form-tooltip-error'
					}
				}
			}); 
			
		}); 
		
	</script>

	

	<script>
		
		var btnCust = ''; 
		$("#picture").fileinput({
		    overwriteInitial: true,
		    maxFileSize: 1500,
		    showClose: false,
		    showCaption: false,
		    showBrowse: false,
		    browseOnZoneClick: true,
		    removeLabel: '',
		    removeIcon: '<i class="glyphicon glyphicon-remove"></i>',
		    removeTitle: 'Cancel or reset changes',
		    elErrorContainer: '#kv-avatar-errors-2',
		    msgErrorClass: 'alert alert-block alert-danger',
		    defaultPreviewContent: '<img src="{{ asset('public/user/img/avatar.png') }}" alt="Missing Image" class="img img-responsive"><span class="text-muted">Click to select <br /><i style="font-size:12px">Image dimesion must be 200x165 with .jpg or .png type</i></span>',
		    layoutTemplates: {main2: '{preview} ' +  btnCust + ' {remove} {browse}'},
		    allowedFileExtensions: ["jpg", "png", "gif"]
		});
	</script>
@endsection

@section ('section-content')
	<div class="container-fluid">
		@include('user.layouts.error')
		@php ($statff_id = "")
		@php ($kh_name = "")
		@php ($en_name = "")
		@php ($cn_name = "")
		@php ($email = "")
		@php ($personal_email = "")
		@php ($phone = "")
        @php ($personal_phone = "")
        @php ($kh_position = "")
        @php ($en_position = "")
        @php ($cn_position = "")
        @php ($status = "")
        @php ($agentcy = "")
        @php ($is_ip_validated = "")
       	@if (Session::has('invalidData'))
            @php ($invalidData = Session::get('invalidData'))
            @php ($statff_id = $invalidData['statff_id'])
            @php ($kh_name = $invalidData['kh_name'])
            @php ($en_name = $invalidData['en_name'])
            @php ($cn_name = $invalidData['cn_name'])
            @php ($email = $invalidData['email'])
            @php ($personal_email = $invalidData['personal_email'])
            @php ($phone = $invalidData['phone'])
            @php ($personal_phone = $invalidData['personal_phone'])
            @php ($kh_position = $invalidData['kh_position'])
            @php ($en_position = $invalidData['en_position'])
            @php ($cn_position = $invalidData['cn_position'])
            @php ($status = $invalidData['status'])
            @php ($agentcy = $invalidData['agentcy'])
            @php ($is_ip_validated = $invalidData['is_ip_validated'])
       	@endif
		<form id="form" action="{{ route($route.'.store') }}" name="form" method="POST"  enctype="multipart/form-data">
			{{ csrf_field() }}
			{{ method_field('PUT') }}
			
			<div class="form-group row">
				<label class="col-sm-2 form-control-label" for="statff_id">Statff ID</label>
				<div class="col-sm-10">
					<input 	id="statff_id"
							name="statff_id"
						   	value = "{{ $statff_id }}"
						   	type="text"
						   	placeholder = "123456"
						   	class="form-control"
						   	data-validation="[L>=2, L<=18, MIXED]"
							data-validation-message="$ must be between 6 and 18 characters. No special characters allowed." />
							
				</div>
			</div>
			<div class="form-group row">
				<label class="col-sm-2 form-control-label" for="kh_content">Language</label>
				<div class="col-sm-1">
					<div class="radio  margin-top-10">
						<input type="radio" name="language_id" id="radio-1" value="1" checked >
						<label for="radio-1">Khmer</label>
					</div>
				</div>
				<div class="col-sm-1">
					<div class="radio  margin-top-10">
						<input type="radio" name="language_id" id="radio-2" value="2" >
						<label for="radio-2">English</label>
					</div>
				</div>
				<div class="col-sm-1">
					<div class="radio  margin-top-10">
						<input type="radio" name="language_id" id="radio-3" value="3" >
						<label for="radio-3">Chinese</label>
					</div>
				</div>
			</div>
			<div class="form-group row">
				<label class="col-sm-2 form-control-label" for="kh_name">Name (KH)</label>
				<div class="col-sm-10">
					<input 	id="kh_name"
							name="kh_name"
						   	value = "{{ $kh_name }}"
						   	type="text"
						   	placeholder = "Eg. Jhon Son"
						   	class="form-control"
						   	data-validation="[L>=1, L<=18]" />
							
				</div>
			</div>
			<div class="form-group row">
				<label class="col-sm-2 form-control-label" for="en_name">Name (EN)</label>
				<div class="col-sm-10">
					<input 	id="en_name"
							name="en_name"
						   	value = "{{ $en_name }}"
						   	type="text"
						   	placeholder = "Eg. Jhon Son"
						   	class="form-control"
						   	data-validation="[L>=1, L<=18]" />
							
				</div>
			</div>
			<div class="form-group row">
				<label class="col-sm-2 form-control-label" for="cn_name">Name (CN)</label>
				<div class="col-sm-10">
					<input 	id="cn_name"
							name="cn_name"
						   	value = "{{ $cn_name }}"
						   	type="text"
						   	placeholder = "Eg. Jhon Son"
						   	class="form-control"
						   	data-validation="[L>=1, L<=18]" />
							
				</div>
			</div>

			<div class="form-group row">
				<label class="col-sm-2 form-control-label" for="email">E-mail</label>
				<div class="col-sm-10">
					<input 	id="email"
							name="email"
							value = "{{ $email }}"
							type="text"
							placeholder = "Eg. you@example.com"
						   	class="form-control"
						   	data-validation="[EMAIL]">
				</div>
			</div>
			<div class="form-group row">
				<label class="col-sm-2 form-control-label" for="personal_email">Personal E-mail</label>
				<div class="col-sm-10">
					<input 	id="personal_email"
							name="personal_email"
							value = "{{ $personal_email }}"
							type="text"
							placeholder = "Eg. you@example.com"
						   	class="form-control"
						   	data-validation="[EMAIL]">
				</div>
			</div>

			<div class="form-group row">
			<label class="col-sm-2 form-control-label" for="phone">Phone</label>
			<div class="col-sm-10">
				<input 	id="phone"
						name="phone"
					   	value = "{{ $phone }}"
					   	type="text" 
					   	placeholder = "Eg. 093123457"
					   	class="form-control"
					   	data-validation="[L>=9, L<=10, numeric]"
						data-validation-message="$ is not correct." 
						data-validation-regex="/(^[00-9].{8}$)|(^[00-9].{9}$)/"
						data-validation-regex-message="$ must start with 0 and has 10 or 11 digits" />
						
			</div>
		</div>
		<div class="form-group row">
				<label class="col-sm-2 form-control-label" for="telegram_chat_id">Telegram Chat ID</label>
				<div class="col-sm-10">
					<input 	id="telegram_chat_id"
							name="telegram_chat_id"
						   	value = ""
						   	type="text"
						   	placeholder = "Please enter your telegram chat ID!"
						   	class="form-control"
						   	data-validation="[L>=1, L<=18]" />
							
				</div>
			</div>
		<div class="form-group row">
			<label class="col-sm-2 form-control-label" for="personal_phone">Personal Phone</label>
			<div class="col-sm-10">
				<input 	id="personal_phone"
						name="personal_phone"
					   	value = "{{ $personal_phone }}"
					   	type="text" 
					   	placeholder = "Eg. 093123457"
					   	class="form-control"
					   	data-validation="[L>=9, L<=10, numeric]"
						data-validation-message="$ is not correct." 
						data-validation-regex="/(^[00-9].{8}$)|(^[00-9].{9}$)/"
						data-validation-regex-message="$ must start with 0 and has 10 or 11 digits" />
						
			</div>
		</div>


		<div class="form-group row">
			<label class="col-sm-2 form-control-label" for="kh_position">Position (KH)</label>
			<div class="col-sm-10">
				<input 	id="kh_position"
						name="kh_position"
					   	value = "{{ $kh_position }}"
					   	type="text"
					   	placeholder = "Eg. Jhon Son"
					   	class="form-control"
					   	data-validation="[L>=2, L<=18, MIXED]"
						data-validation-message="$ must be between 6 and 18 characters. No special characters allowed." />
						
			</div>
		</div>
		<div class="form-group row">
			<label class="col-sm-2 form-control-label" for="en_position">Position (EN)</label>
			<div class="col-sm-10">
				<input 	id="en_position"
						name="en_position"
					   	value = "{{ $en_position }}"
					   	type="text"
					   	placeholder = "Eg. Jhon Son"
					   	class="form-control"
					   	data-validation="[L>=2, L<=18, MIXED]"
						data-validation-message="$ must be between 6 and 18 characters. No special characters allowed." />
						
			</div>
		</div>
		<div class="form-group row">
			<label class="col-sm-2 form-control-label" for="cn_position">Position (CN)</label>
			<div class="col-sm-10">
				<input 	id="cn_position"
						name="cn_position"
					   	value = "{{ $cn_position}}"
					   	type="text"
					   	placeholder = "Eg. Jhon Son"
					   	class="form-control"
					   	data-validation="[L>=2, L<=18, MIXED]"
						data-validation-message="$ must be between 6 and 18 characters. No special characters allowed." />
						
			</div>
		</div>

			<div class="form-group row">
				<label for="position_id" class="col-sm-2 form-control-label">Position</label>
				<div class="col-sm-10">
					<select id="position_id" name="position_id" class="form-control">
						<option value="2" >User</option>
						<option value="1}" >Admin</option>
					</select>
				</div>
			</div>

			<div class="form-group row">
				<label class="col-sm-2 form-control-label" for="password">Password</label>
				<div class="col-sm-10">
					<input 	id="password"
							name="password"
						   	value = ""
						   	type="password"
						   	placeholder = ""
						   	class="form-control"
						   	data-validation="[L>=6, L<=18]"
							data-validation-message="$ must be between 6 and 18 characters." />
				</div>
			</div>
			<div class="form-group row">
				<label class="col-sm-2 form-control-label" for="confirm_password">Confirm Password</label>
				<div class="col-sm-10">
					<input 	id="confirm_password"
							name="confirm_password"
						   	value = ""
						   	type="password"
						   	placeholder = ""
						   	class="form-control"
						   	data-validation="[L>=6, L<=18]"
							data-validation-message="$ must be between 6 and 18 characters." />
				</div>
			</div>
			<div class="form-group row">
				<label class="col-sm-2 form-control-label" for="email">Image</label>
				<div class="col-sm-10">
					<div class="kv-avatar center-block">
				        <input id="picture" name="picture" type="file" class="file-loading">
				    </div>
				</div>
			</div>
			
			<div class="form-group row">
				<label class="col-sm-2 form-control-label" for="description">Description</label>
				<div class="col-sm-10">
					<div class="summernote-theme-1">
						<textarea id="description" name="description" class="form-control"></textarea>
					</div>	
				</div>
			</div>

			<div class="form-group row">
				<label class="col-sm-2 form-control-label"></label>
				<div class="col-sm-10">
					<button type="submit" class="btn btn-success"> <fa class="fa fa-plus"></i> Create</button>
				</div>
			</div>
		</form>
	</div>

@endsection

grobarting/resources/views/user/user/user/tabForm.blade.php
@extends('user.user.user.main')
@section ('section-css')
	@yield ('tab-css')
@endsection

@section ('section-js')
	@yield ('tab-js')
@endsection

@section ('section-content')
		
			
	<section class="tabs-section">
		<div class="tabs-section-nav tabs-section-nav-icons">
			<div class="tbl">
				<ul class="nav" role="tablist">
					<li class="nav-item">
						
						<a class="nav-link @yield ('tab-active-edit')" onclick="window.location.href='{{ route('user.user.user.edit', $id) }}'" href="#" role="tab" data-toggle="tab">
							<span class="nav-link-in">
								<i class="fa fa-user"></i> Overview
							</span>
						</a>
					</li>
					
					<li class="nav-item">
						<a class="nav-link @yield ('tab-active-system-permision')" onclick="window.location.href='{{ route('user.user.user.system-permision', $id) }}' " href="#" role="tab" data-toggle="tab">
							<span class="nav-link-in">
								<i class="glyphicon glyphicon-stats"></i> System Permisions
							</span>
						</a>
					</li>
					<li class="nav-item">
						<a class="nav-link @yield ('tab-active-properties')" onclick="window.location.href='{{ route('user.user.user.properties', $id) }}' " href="#" role="tab" data-toggle="tab">
							<span class="nav-link-in">
								<i class="fa fa-building"></i> Properties In Charge
							</span>
						</a>
					</li>
					<li class="nav-item">
						<a class="nav-link @yield ('tab-active-logs')" onclick="window.location.href='{{ route('user.user.user.logs', $id) }}' " href="#" role="tab" data-toggle="tab">
							<span class="nav-link-in">
								<i class="glyphicon glyphicon-stats"></i> Logs
							</span>
						</a>
					</li>
					
				</ul>
			</div>
		</div><!--.tabs-section-nav-->

		<div class="tab-content">
			<div role="tabpanel" class="tab-pane fade in active">
				<div id="tab-content-cnt" class="container-fluid">
					@yield ('tab-content')
				</div>
			</div>
		</div><!--.tab-content-->
	</section><!--.tabs-section-->
				
	


@endsection